all:
  routers:
    hosts:
      R1:
        ansible_host: 192.168.10.10
      R2:
        ansible_host: 192.168.10.11
      R3:
        ansible_host: 192.168.10.12
    vars:
          ansible_user: admin
          ansible_password: telecomS144

