- name: Routing Protocol OSPF Configuration
  hosts: routers
  gather_facts: no
  vars:
    ansible_connection: network_cli
  tasks:
    - name: configure OSPF
      ios_config:
        lines:
          - "router ospf 1"
          - "network 192.168.10.0 0.0.0.255 area 0"